camp-python-2021-cofounders-finder-develop/apps/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        views.ChatMainPageView.as_view(),
        name="chat_main_page",
    ),
    path(
        "<int:user_pk>/",
        views.ChatRoomView.as_view(),
        name="chat_room",
    ),
]

camp-python-2021-cofounders-finder-develop/apps/startups/urls.py
from django.urls import path

from . import views

app_name = "startups"
urlpatterns = [
    path(
        "",
        views.startups.StartupsListView.as_view(),
        name="startups_list",
    ),
    path(
        "<int:pk>/",
        views.startups.StartupsDetailView.as_view(),
        name="startup_detail",
    ),
    path(
        "vacancies/",
        views.vacancies.VacanciesListView.as_view(),
        name="vacancies_list",
    ),
    path(
        "vacancies/<int:pk>",
        views.vacancies.VacancyDetailView.as_view(),
        name="vacancy_detail",
    ),
    path(
        "create",
        views.startups.StartupCreateView.as_view(),
        name="startup_create",
    ),
    path(
        "<int:pk>/update",
        views.startups.StartupUpdateView.as_view(),
        name="startup_update",
    ),
    path(
        "<int:pk>/delete",
        views.startups.StartupDeleteView.as_view(),
        name="startup_delete",
    ),
    path(
        "vacancies/<int:pk>/update",
        views.vacancies.VacancyUpdateView.as_view(),
        name="vacancy_update",
    ),
    path(
        "vacancies/<int:pk>/delete",
        views.vacancies.VacancyDeleteView.as_view(),
        name="vacancy_delete",
    ),
]

camp-python-2021-cofounders-finder-develop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
  <link rel="stylesheet" href={% static "css/form.css" %}>
  <link rel="stylesheet" href={% static "css/content.css" %}>
  <link rel="stylesheet" href={% static "css/sidebar.css" %}>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>
  <script type="text/javascript"
          src="{% static 'js/jquery.formset.js' %}"></script>
  <style>

    {% block style %}
    {% endblock %}
  </style>
</head>


<body>

{% block header %}
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href={% url "home" %}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href={% url "startups:vacancies_list" %}>Vacancies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href={% url "cvs" %}>CVs</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href={% url "startups:startups_list" %}>Startups</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Create startup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href={% url "chat_main_page" %}>Chat</a>
          </li>
        {% endif %}
      </ul>
      <div id="app"></div>
      <ul class="nav">
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href={% url "login" %}>Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href={% url "signup" %}>Sign up</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" href={% url "account" %}>Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href={% url "logout" %}>Log out</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

{% endblock %}
<div class="content">
  {% block content %}
  {% endblock %}
</div>
{% block script %}
{% endblock %}
<script src="https://unpkg.com/vue@3.2.2/dist/vue.global.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue3-sfc-loader/dist/vue3-sfc-loader.js"></script>
<script>
  const options = {
    moduleCache: {
      vue: Vue
    },
    async getFile(url) {

      const res = await fetch(url);
      if (!res.ok)
        throw Object.assign(new Error(res.statusText + ' ' + url), {res});
      return {
        getContentData: asBinary => asBinary ? res.arrayBuffer() : res.text(),
      }
    },
    addStyle(textContent) {

      const style = Object.assign(document.createElement('style'), {textContent});
      const ref = document.head.getElementsByTagName('style')[0] || null;
      document.head.insertBefore(style, ref);
    },
  }

  const {loadModule} = window['vue3-sfc-loader'];
  const app = Vue.createApp({
    components: {
      'datalist-component': Vue.defineAsyncComponent(() => loadModule('/static/js/vue-components/DataList.vue', options))
    },
    template: '<datalist-component></datalist-component>'
  });

  app.mount('#app');
</script>
</body>
</html>

camp-python-2021-cofounders-finder-develop/templates/base_with_new_message_notification.html
{% extends "base.html" %}
{% load static %}
{% block script %}
{% include "chat/new_message_notification.html" %}
{% endblock %}

camp-python-2021-cofounders-finder-develop/templates/email_base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  {% block email_body %}
  {% endblock %}
</body>
</html>

camp-python-2021-cofounders-finder-develop/templates/index.html
{% extends "base_with_new_message_notification.html" %}
{% load static %}
{% block content %}
    <div class="home">
      <h1>Welcome to Cofounder finder project!</h1>
      <h2>Create your first startup and find cofounders for it!</h2>
      <p>
        Our service allows you to create resumes, startups and vacancies, find
        colleagues and like-minded people to implement your ideas. You can post
        your CVs by specifying your skills. You can apply for vacancies,
        confirm or deny the skills of associates on their resume. You can also
        chat with the person who posted the resume that interests you.
      </p>
      <a class="btn btn-success" href="{% url "startups:startup_create" %}">Start
        a startup</a>
      <h2>Find good vacancy in startup and become cofounder of it!</h2>
      <p>
        A community where people help each other create useful companies and
        products. Wherever you were born and wherever you live now. You can do
        courageous and necessary things with like-minded people.
      </p>
    </div>
{% endblock %}